#!/bin/bash
#
# To use it, add the following alias in your .bashrc:
#
# alias cdw='. cdwi'
#

[ -f ~/.WD ] || { echo "No ~/.WD file found. Use 'setw' to set a work directory first." 1>&2; return 1; }
cd $(cat ~/.WD)

