#!/usr/bin/env bash
#
# Overwrites target libraries (bash.shlib, json.shlib) with the reference copy, only if necessary.
#

SOURCES="bash.shlib json.shlib"

function main() {

    for i in ${SOURCES}; do
        sync-file ${i}
    done
}

function sync-file() {

    local file_name=$1
    [[ -z ${file_name} ]] && { echo "'file_name' not provided" 1>&2; exit 1; }

    local source_file=$(dirname $0)/${file_name}
    [[ -f ${source_file} ]] || { echo "file does not exist: ${source_file}" 1>&2; exit 1; }
    local target_file=~/bash_shlib_copy/${file_name}

    if [[ -f ${target_file} && ${target_file} -nt ${source_file} ]]; then

        if ! diff ${target_file} ${source_file} >/dev/null; then
            echo "the target file ${target_file} seems to be newer than the source file ${source_file}, and difference exist, check differences and reconcile manually"
            exit 1
        fi

        #
        # no differences exist, even if the target file is newer, exit
        #

        echo "${file_name}: nothing changed"
        return 0
    fi

    cp ${source_file} ${target_file} && echo "${file_name}: overwritten" || echo "failed to copy" 1>&2;
}

main "$@"



