#!/usr/bin/env bash
#
# Overwrites target bash.shlib with the reference copy, only if necessary.
#

source=$(dirname $0)/bash.shlib
target=~/bash_shlib_copy/bash.shlib

if [[ ${target} -nt ${source} ]]; then

    if ! diff ${target} ${source} >/dev/null; then
        echo "the target file ${target} seems to be newer than the source file ${source}, and difference exist, check differences and reconcile manually"
        exit 1
    fi

    #
    # no differences exist, even if the target file is newer, silently exit
    #

    echo "nothing changed"

    exit 0
fi

cp ./bash.shlib ${target} && echo "overwrote ${target}" || echo "failed to copy" 1>&2;

