#!/usr/bin/env bash

for i in bash.shlib jenkins.shlib; do [ -f $(dirname $0)/../lib/${i} ] && source $(dirname $0)/../lib/${i} || { echo "[error]: $(dirname $0)/../lib/${i} not found" 1>&2; exit 1; } done

VERSION=0.2.0

# The Jenkins base URL (https://<host>/<instance-name>/blue/rest/organizations/jenkins). Must not end with slash.
JENKINS_BASE_URL=UNINITIALIZED # set by initialize-global-context()
JENKINS_BASE64_AUTH=UNINITIALIZED # set by initialize-global-context()
JENKINS_TMP_DIR=/tmp # temporary directory that contains various temporary files per run, created and set by initialize-global-context()

TMP_FILE_NAME_PREFIX=jenq

function usage() {
cat <<EOF

Jenkins instance query tool.

    $(basename $0) [common-options] <command> [command-options]

Common Options:

    --host-url specifies the URL of the Jenkins instance host (ex: https://jenkins.example.com). The same value can
        be provided with JENKINS_HOST_URL environment variable. If both the environment variable and command line
        options are provided, command line value takes precedence.

    --username specifies the user name to authenticated against the Jenkins instance. The same value can be provided
        with JENKINS_USERNAME environment variable. If both the environment variable and command line options are
        provided, command line value takes precedence.

    --password specifies the password to use to authenticated against the Jenkins instance. The same value can be
        provided with JENKINS_PASSWORD environment variable. If both the environment variable and command line options
        are provided, command line value takes precedence.

    --instance-name specifies the name of the Jenkins instance (ex: release).  The same value can be provided with
        JENKINS_INSTANCE_NAME environment variable. If both the environment variable and command line options are
        provided, command line value takes precedence.

    --preserve-tmp-dir instructs the command to preserve the content of the temporary directory for the run.

Commands:

    pipelines - return pipelines, optionally filtered by pipeline type.

    pipeline - display a specific pipeline information.

    branches - return branches for a multi-branch pipeline.

    branch - display a specific branch information.

    runs - return runs for a branch.

    run - display a specific run information.

    nodes - return nodes for a run

    node - display a specific node information.

    log - pull the execution log for a node.

Examples:

Display the node name and ID for a run:

    $(basename $0) nodes --json <pipeline-name> <branch> <run-id> | jq -r '.[] | (.id + " " + .displayName)'

Display the names of the nodes that failed:

    $(basename $0) nodes --json <pipeline-name> <branch> <run-id> | jq -r 'select(.result=="FAILURE") | .displayName'

Display the nodes whose name match a certain pattern and their result:

    $(basename $0) nodes --json <pipeline-name> <branch> <run-id> | jq -r 'select(.displayName | contains("something")) | (.displayName + ": " + .result)'

Individual command help can be obtained with:

     $(basename $0) help <command>

EOF
}

function main() {

    process-common-arguments "$@" && set -- "${ARGS[@]}" || { echo "failed to process common arguments" 1>&2; exit 1; }

    if ${HELP}; then
        [[ -n $1 ]] && { help-$1; exit 0; }
        usage; exit 0;
    fi

    [[ -z $1 ]] && { usage; exit 0; }

    unset ARGS; declare -a ARGS
    declare -A OPTIONS
    OPTIONS["--host-url"]="string"
    OPTIONS["--username"]="string"
    OPTIONS["--password"]="string"
    OPTIONS["--instance-name"]="string"
    OPTIONS["--preserve-tmp-dir"]="boolean"
    process-options "$@"

    local host_url=${OPTIONS["--host-url"]:-${JENKINS_HOST_URL}}
    [[ -z ${host_url} ]] && fail "Jenkins host URL not provided; use --host-url command line option or set JENKINS_HOST_URL environment variable"
    local username=${OPTIONS["--username"]:-${JENKINS_USERNAME}}
    [[ -z ${username} ]] && fail "Jenkins user name not provided; use --username command line option or set JENKINS_USERNAME environment variable"
    local password=${OPTIONS["--password"]:-${JENKINS_PASSWORD}}
    [[ -z ${password} ]] && fail "Jenkins password not provided; use --password command line option or set JENKINS_PASSWORD environment variable"
    local instance_name=${OPTIONS["--instance-name"]:-${JENKINS_INSTANCE_NAME}}
    [[ -z ${instance_name} ]] && fail "Jenkins instance name not provided; use --instance-name command line option or set JENKINS_INSTANCE_NAME environment variable"

    initialize-global-context ${host_url} ${username} ${password} ${instance_name} ${OPTIONS["--preserve-tmp-dir"]}

    set -- "${ARGS[@]}"

    local command=$1

    shift

    do-${command} "$@"
}

main "$@"